<?php
require_once '../../../inc/lib/base.class.php';
\Security\AdminAccount::requireSuper();
$accountNo = isset($accountNo) ? (int) $accountNo : (int) ($_GET['no'] ?? 0);
$account = $accountNo > 0 ? \Security\AdminAccount::findByNo($accountNo) : [];
if ($accountNo > 0 && !$account) { http_response_code(404); exit('계정을 찾을 수 없습니다.'); }
if ($account) \Security\PrivacyLogger::record('view', 'admin_account', $accountNo, (string) $account['uname'], '관리자 계정 상세 열람');
$creating = $accountNo === 0; $depthnum = 8; $pagenum = 1;
$flash = (string) ($_SESSION['account_flash'] ?? ''); $flashError = !empty($_SESSION['account_flash_error']); unset($_SESSION['account_flash'], $_SESSION['account_flash_error']);
include_once '../../inc/admin.title.php'; include_once '../../inc/admin.css.php'; include_once '../../inc/admin.js.php';
$e = static function ($v): string { return htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); };
?>
</head><body class="no-account-page"><div class="no-wrap"><?php include_once '../../inc/admin.header.php'; ?><main class="no-app no-container" data-pii-lock><?php include_once '../../inc/admin.drawer.php'; ?><section class="no-content">
<div class="no-toolbar"><div class="no-toolbar-container no-flex-stack"><div class="no-page-indicator"><h1 class="no-page-title"><?=$creating ? '계정 생성' : '계정 수정'?></h1></div></div></div>
<div class="no-content-container"><div class="no-card"><div class="no-card-header no-card-header--detail"><h2 class="no-card-title"><?=$creating ? '신규 계정 등록' : '계정 정보 수정'?></h2></div><div class="no-card-body"><?php if ($flash !== ''): ?><p class="account-flash" role="alert"><?=$e($flash)?></p><?php endif; ?><form class="account-form no-admin-column no-admin-column--detail" method="post" action="/admin/pages/account/process.php" autocomplete="off"><input type="hidden" name="mode" value="<?=$creating ? 'create' : 'update'?>"><?php if (!$creating): ?><input type="hidden" name="no" value="<?=$accountNo?>"><?php endif; ?>
<div class="no-admin-block"><h3 class="no-admin-title"><label for="role_code">권한</label></h3><div class="no-admin-content"><div class="no-radio-form no-list" id="role_code" role="group" aria-label="권한"><?php foreach (['super'=>'최고 관리자','admin'=>'일반 관리자'] as $value=>$label): ?><label><div class="no-radio-box"><input type="radio" name="role_code" value="<?=$value?>" <?=($account['role_code'] ?? 'admin') === $value ? 'checked' : ''?> required><span><i class="bx bx-radio-circle-marked"></i></span></div><span class="no-radio-text"><?=$label?></span></label><?php endforeach; ?></div></div></div>
<div class="no-admin-block"><h3 class="no-admin-title"><label for="uid">아이디</label></h3><div class="no-admin-content"><input class="no-input--detail" id="uid" name="uid" value="<?=$e($account['uid'] ?? '')?>" <?=$creating ? 'required pattern="[A-Za-z0-9_]{4,20}"' : 'readonly'?> maxlength="20" autocomplete="off"></div></div>
<?php if ($creating): ?><div class="no-admin-block"><h3 class="no-admin-title"><label for="password">초기 비밀번호</label></h3><div class="no-admin-content"><input class="no-input--detail" id="password" type="password" name="password" required minlength="8" maxlength="72" autocomplete="new-password"><small class="account-help">8~72바이트, 영문 대문자·소문자·숫자·특수문자 중 3가지 이상을 포함하세요.</small></div></div><div class="no-admin-block"><h3 class="no-admin-title"><label for="password_confirm">초기 비밀번호 확인</label></h3><div class="no-admin-content"><input class="no-input--detail" id="password_confirm" type="password" name="password_confirm" required minlength="8" maxlength="72" autocomplete="new-password"></div></div><?php endif; ?>
<div class="no-admin-block"><h3 class="no-admin-title"><label for="uname">이름</label></h3><div class="no-admin-content"><input class="no-input--detail" id="uname" name="uname" value="<?=$e($account['uname'] ?? '')?>" required maxlength="20"></div></div>
<div class="no-admin-block"><h3 class="no-admin-title"><label for="email">이메일</label></h3><div class="no-admin-content"><input class="no-input--detail" id="email" type="email" name="email" value="<?=$e($account['email'] ?? '')?>" required maxlength="190" autocomplete="email"></div></div>
<div class="no-admin-block"><h3 class="no-admin-title"><label for="active_status">상태</label></h3><div class="no-admin-content"><div class="no-radio-form no-list" id="active_status" role="group" aria-label="상태"><?php foreach (['Y'=>'활성','N'=>'비활성'] as $value=>$label): ?><label><div class="no-radio-box"><input type="radio" name="active_status" value="<?=$value?>" <?=($account['active_status'] ?? 'Y') === $value ? 'checked' : ''?> required><span><i class="bx bx-radio-circle-marked"></i></span></div><span class="no-radio-text"><?=$label?></span></label><?php endforeach; ?></div></div></div>
<div class="account-buttons no-items-center center"><a class="no-btn no-btn--big no-btn--normal" href="/admin/pages/account/index.php">목록</a><button class="no-btn no-btn--big no-btn--main" type="submit"><?=$creating ? '등록' : '저장'?></button></div></form>
<?php if (!$creating && $accountNo !== (int) ($_SESSION['no_adm_login_no'] ?? 0)): ?><form class="account-form account-reset no-admin-column no-admin-column--detail" method="post" action="/admin/pages/account/process.php"><input type="hidden" name="mode" value="reset_password"><input type="hidden" name="no" value="<?=$accountNo?>"><h2>임시 비밀번호 설정</h2><p class="account-help">저장 즉시 기존 세션이 종료되며 다음 로그인에서 본인 비밀번호 변경을 강제합니다.</p><div class="no-admin-block"><h3 class="no-admin-title"><label for="reset_password">임시 비밀번호</label></h3><div class="no-admin-content"><input class="no-input--detail" id="reset_password" type="password" name="password" required minlength="8" maxlength="72" autocomplete="new-password"></div></div><div class="no-admin-block"><h3 class="no-admin-title"><label for="reset_password_confirm">임시 비밀번호 확인</label></h3><div class="no-admin-content"><input class="no-input--detail" id="reset_password_confirm" type="password" name="password_confirm" required minlength="8" maxlength="72" autocomplete="new-password"></div></div><div><button class="no-btn no-btn--big no-btn--main" type="submit">임시 비밀번호 저장</button></div></form><?php endif; ?>
</div></div></div></section></main><?php include_once '../../inc/admin.footer.php'; ?></div></body></html>
